# Site settings
title: 优雅角落
email: happypeter1983@gmail.com
description: 不要停止创作！
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://happycasts.net" # the base hostname & protocol for your site
twitter_username: happypeter1983
github_username:  happypeter

# Build settings
markdown: kramdown
